name: vidok
channels:
  - rdkit
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - rdkit=2020.09.1.0
  - numpy=1.19.5
  - pandas==1.3.2
  - scikit-learn==0.24.2
  - biopandas==0.2.9
  - matplotlib==3.4.3
  - openbabel=3.1.1
  - notebook
